#lang racket
(define error "Ошибка! Количество секунд не может быть больше 60")
(display "Перевести минуты и секунды в секунды")
(newline)
(display "Введите время.")
(newline)
(define (min)
  (write "Сколько минут: ")
  (read))
(define (sec)
  (write "Сколько секунд: ")
  (read))
(define (S min sec)
(display "Ответ: ")
  (display (+ (* min 60) sec))
  (display " секунд")
  (newline))
(define (V min sec)
  (if (< sec 61)
      (S min sec)
      error))
(V(min)(sec))