#lang racket
(define error "Ошибка! Радиус отверстия не может быть больше радиуса кольца")
(define pi 3.14)
(display "Вычисление площади кольца.")
(newline)
(display "Введите исходные данные.")
(newline)
(define (r1)
  (write "Радиус кольца (см)= ")
  (read))
(define (r2)
  (write "Радиус отверстия (см)= ")
  (read))
(define (S r1 r2)
(display "Площадь кольца = ")
  (display (* pi (- (expt r1 2) (expt r2 2))))
  (display " кв.см")
  (newline))
(define (V r1 r2)
  (if (> r1 r2)
      (S r1 r2)
      error))
(V(r1)(r2))