#lang racket
(define pi 3.14)
(display "Вычисление объема цилиндра.")
(newline)
(display "Введите исходные данные.")
(newline)
(define (r)
  (write "Радиус основания (см) = ")
  (read))
(define (h)
  (write "Высота цилиндра (см) = ")
  (read))
(define (V r h)
(display "объем цилиндра = ")
  (display (* pi h (r 2))))
  (display " руб.")
  (newline))
(V(r)(h))